import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { parse as jsonToCsv } from 'json2csv';

class ExportService {
  /**
   * Generate PDF report
   */
  async generatePDF(analytics, PDFDocCtor = PDFDocument) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocCtor({ margin: 50 });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(24).text('Analytics Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
        doc.text(`Period: ${new Date(analytics.period.start).toLocaleDateString()} - ${new Date(analytics.period.end).toLocaleDateString()}`, { align: 'center' });
        doc.moveDown(2);

        // Dashboard Metrics
        doc.fontSize(18).text('Dashboard Metrics', { underline: true });
        doc.moveDown();

        const metrics = analytics.metrics;
        doc.fontSize(12);
        doc.text(`Total Revenue: Rs. ${metrics.totalRevenue.total.toFixed(2)}`);
        doc.text(`Platform Fees: Rs. ${metrics.platformFees.total.toFixed(2)}`);
        doc.text(`Active Users (Daily/Weekly/Monthly): ${metrics.activeUsers.daily}/${metrics.activeUsers.weekly}/${metrics.activeUsers.monthly}`);
        doc.text(`Jobs Posted: ${metrics.jobStats.posted}`);
        doc.text(`Jobs Completed: ${metrics.jobStats.completed}`);
        doc.text(`Completion Rate: ${metrics.jobStats.completionRate}%`);
        doc.text(`Average Job Value: Rs. ${metrics.jobStats.avgValue.toFixed(2)}`);
        doc.moveDown(2);

        // Top Freelancers
        doc.fontSize(18).text('Top Freelancers', { underline: true });
        doc.moveDown();
        metrics.topFreelancers.slice(0, 5).forEach((freelancer, i) => {
          doc.fontSize(12).text(`${i + 1}. ${freelancer.name} - ${freelancer.completedJobs} jobs, Rs. ${freelancer.totalEarnings.toFixed(2)}`);
        });
        doc.moveDown(2);

        // Top Clients
        doc.fontSize(18).text('Top Clients', { underline: true });
        doc.moveDown();
        metrics.topClients.slice(0, 5).forEach((client, i) => {
          doc.fontSize(12).text(`${i + 1}. ${client.name} - ${client.jobsPosted} jobs, Rs. ${client.totalSpent.toFixed(2)}`);
        });
        doc.moveDown(2);

        // Verification Stats
        doc.fontSize(18).text('Verification Statistics', { underline: true });
        doc.moveDown();
        doc.fontSize(12);
        doc.text(`Verified Users: ${metrics.verificationStats.verified}`);
        doc.text(`Pending Verification: ${metrics.verificationStats.pending}`);
        doc.text(`Rejected: ${metrics.verificationStats.rejected}`);
        doc.moveDown(2);

        // Revenue Report
        if (analytics.revenue.length > 0) {
          doc.addPage();
          doc.fontSize(18).text('Monthly Revenue', { underline: true });
          doc.moveDown();
          analytics.revenue.forEach(item => {
            const monthName = new Date(item._id.year, item._id.month - 1).toLocaleString('default', { month: 'long', year: 'numeric' });
            doc.fontSize(12).text(`${monthName}: Rs. ${item.revenue.toFixed(2)} (${item.jobCount} jobs)`);
          });
        }

        // Category Distribution
        if (analytics.categories.length > 0) {
          doc.addPage();
          doc.fontSize(18).text('Job Categories', { underline: true });
          doc.moveDown();
          analytics.categories.forEach(cat => {
            doc.fontSize(12).text(`${cat._id}: ${cat.count} jobs, Rs. ${cat.totalValue.toFixed(2)}`);
          });
        }

        // Footer
        doc.fontSize(10).text('Generated by Linkify Platform', { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate Excel report
   */
  async generateExcel(analytics, WorkbookCtor = ExcelJS.Workbook) {
    const workbook = new WorkbookCtor();
    workbook.creator = 'Linkify Platform';
    workbook.created = new Date();

    // Dashboard Metrics Sheet
    const metricsSheet = workbook.addWorksheet('Dashboard Metrics');
    metricsSheet.columns = [
      { header: 'Metric', key: 'metric', width: 30 },
      { header: 'Value', key: 'value', width: 20 }
    ];

    const metrics = analytics.metrics;
    metricsSheet.addRows([
      { metric: 'Total Revenue', value: `Rs. ${metrics.totalRevenue.total.toFixed(2)}` },
      { metric: 'Platform Fees', value: `Rs. ${metrics.platformFees.total.toFixed(2)}` },
      { metric: 'Active Users (Daily)', value: metrics.activeUsers.daily },
      { metric: 'Active Users (Weekly)', value: metrics.activeUsers.weekly },
      { metric: 'Active Users (Monthly)', value: metrics.activeUsers.monthly },
      { metric: 'Jobs Posted', value: metrics.jobStats.posted },
      { metric: 'Jobs Completed', value: metrics.jobStats.completed },
      { metric: 'Completion Rate', value: `${metrics.jobStats.completionRate}%` },
      { metric: 'Average Job Value', value: `Rs. ${metrics.jobStats.avgValue.toFixed(2)}` },
      { metric: 'Verified Users', value: metrics.verificationStats.verified },
      { metric: 'Pending Verification', value: metrics.verificationStats.pending }
    ]);

    // Top Freelancers Sheet
    const freelancersSheet = workbook.addWorksheet('Top Freelancers');
    freelancersSheet.columns = [
      { header: 'Name', key: 'name', width: 25 },
      { header: 'Email', key: 'email', width: 30 },
      { header: 'Completed Jobs', key: 'jobs', width: 15 },
      { header: 'Total Earnings', key: 'earnings', width: 15 }
    ];
    metrics.topFreelancers.forEach(f => {
      freelancersSheet.addRow({
        name: f.name,
        email: f.email,
        jobs: f.completedJobs,
        earnings: `Rs. ${f.totalEarnings.toFixed(2)}`
      });
    });

    // Top Clients Sheet
    const clientsSheet = workbook.addWorksheet('Top Clients');
    clientsSheet.columns = [
      { header: 'Name', key: 'name', width: 25 },
      { header: 'Email', key: 'email', width: 30 },
      { header: 'Jobs Posted', key: 'posted', width: 15 },
      { header: 'Total Spent', key: 'spent', width: 15 }
    ];
    metrics.topClients.forEach(c => {
      clientsSheet.addRow({
        name: c.name,
        email: c.email,
        posted: c.jobsPosted,
        spent: `Rs. ${c.totalSpent.toFixed(2)}`
      });
    });

    // Revenue Report Sheet
    const revenueSheet = workbook.addWorksheet('Revenue Report');
    revenueSheet.columns = [
      { header: 'Month', key: 'month', width: 20 },
      { header: 'Revenue', key: 'revenue', width: 15 },
      { header: 'Platform Fee', key: 'fee', width: 15 },
      { header: 'Job Count', key: 'count', width: 15 }
    ];
    analytics.revenue.forEach(r => {
      const monthName = new Date(r._id.year, r._id.month - 1).toLocaleString('default', { month: 'long', year: 'numeric' });
      revenueSheet.addRow({
        month: monthName,
        revenue: `Rs. ${r.revenue.toFixed(2)}`,
        fee: `Rs. ${r.platformFee.toFixed(2)}`,
        count: r.jobCount
      });
    });

    // Category Distribution Sheet
    const categoriesSheet = workbook.addWorksheet('Categories');
    categoriesSheet.columns = [
      { header: 'Category', key: 'category', width: 30 },
      { header: 'Job Count', key: 'count', width: 15 },
      { header: 'Total Value', key: 'value', width: 15 }
    ];
    analytics.categories.forEach(c => {
      categoriesSheet.addRow({
        category: c._id,
        count: c.count,
        value: `Rs. ${c.totalValue.toFixed(2)}`
      });
    });

    const buffer = await workbook.xlsx.writeBuffer();
    return buffer;
  }

  /**
   * Generate CSV report
   */
  async generateCSV(analytics) {
    const data = [];

    // Flatten metrics data
    const metrics = analytics.metrics;
    data.push({
      type: 'Metric',
      name: 'Total Revenue',
      value: metrics.totalRevenue.total.toFixed(2),
      unit: 'Rs.'
    });
    data.push({
      type: 'Metric',
      name: 'Platform Fees',
      value: metrics.platformFees.total.toFixed(2),
      unit: 'Rs.'
    });
    data.push({
      type: 'Metric',
      name: 'Active Users (Daily)',
      value: metrics.activeUsers.daily,
      unit: 'users'
    });
    data.push({
      type: 'Metric',
      name: 'Jobs Posted',
      value: metrics.jobStats.posted,
      unit: 'jobs'
    });
    data.push({
      type: 'Metric',
      name: 'Jobs Completed',
      value: metrics.jobStats.completed,
      unit: 'jobs'
    });

    // Add revenue data
    analytics.revenue.forEach(r => {
      const monthName = new Date(r._id.year, r._id.month - 1).toLocaleString('default', { month: 'long', year: 'numeric' });
      data.push({
        type: 'Revenue',
        name: monthName,
        value: r.revenue.toFixed(2),
        unit: 'Rs.'
      });
    });

    // Add category data
    analytics.categories.forEach(c => {
      data.push({
        type: 'Category',
        name: c._id,
        value: c.count,
        unit: 'jobs'
      });
    });

    const csv = jsonToCsv(data, {
      fields: ['type', 'name', 'value', 'unit']
    });

    return csv;
  }
}

export default new ExportService();
